### ISSUE TITLE
Support on ubuntu?and so file

### ISSUE THREAD

**Issue by jordanmv1c** [episage/SharpNFC#7]
...

**Comment by episage** [comment]
`Can i install the libnfc with apt_get install libnfc-dev`
Yes

`And on the same way install the pcsc?`
Yes

```text
How mono know where to looking this file?
Do i need to put it on the project folder?(where this file exist?)
```
You don't need to do that provided that you compile https://libnfc.googlecode.com/files/libnfc-1.7.0.tar.bz2 as in the README.md. I.e:
```
wget https://libnfc.googlecode.com/files/libnfc-1.7.0.tar.bz2
tar xvjf libnfc-1.7.0.tar.bz2

cd libnfc-1.7.0
./configure --prefix=/usr
make
make install
cd ..
```

**Comment by jordanmv1c** [comment]
I wil try to explain myself more clearly.
You said that i can install on ubuntu libnfc and pcsc with apt-get install libnfc-dev/pcsc.

Now after that i want to use on sharp nfc
I install mono.
On c# code I saw dll inmport to libnfc.so
Where the code looking for this file?
I must to compail like the way you show on readme? Not like i done?

Thank

**Comment by episage** [comment]
You must do:
```
wget https://libnfc.googlecode.com/files/libnfc-1.7.0.tar.bz2
tar xvjf libnfc-1.7.0.tar.bz2

cd libnfc-1.7.0
./configure --prefix=/usr
make
make install
cd ..
```
for C# code to see libnfc.so.
Amen.

**Comment by jordanmv1c** [comment]
Ok
So what is the step on ubuntu?
I want to use with ACR122U so i must install the pcsc.
So the step is
1. Apt-get install libnfc-dev
2. apt-get install pcsc
3.
wget https://libnfc.googlecode.com/files/libnfc-1.7.0.tar.bz2
tar xvjf libnfc-1.7.0.tar.bz2

cd libnfc-1.7.0
./configure --prefix=/usr
make
make install
cd ..
To compail for libnfc.so

4.
create /etc/modprobe.d/blacklist-libnfc.conf with this content:

blacklist pn533
blacklist nfc


Or if i want to use on sharpnfc and i need to compail to libnfcb.so i dont need to do step 1, need to replace it with step 3

Thanks

**Comment by episage** [comment]
1. Please use proper English otherwise I will not read your messages. Your last message looks like rubbish.
2. Tell me what you tried and where you are stuck
